import Link from "next/link";
import { PageFooter, PageHero, SiteHeader } from "../site-chrome";
import { sitePath } from "../site-path";

const sectors = [
  { id:"government", number:"01", title:"Government, defence & security", line:"Confidence in demanding environments.", copy:"We support teams working with sensitive data, regulated processes and complex operational decisions. Our approach brings security, assurance and explainability into the work from the start.", points:["Responsible and explainable AI","Operational decision support","Secure data and cloud platforms","Digital forensics and assurance"], video:"/sector-defence.mp4", poster:"/sector-defence-poster.jpg", filmTitle:"From the lab to the front line." },
  { id:"agrifood", number:"02", title:"Agrifood", line:"Better evidence from field to fork.", copy:"We help organisations connect fragmented data, understand environmental and operational risk, and make faster decisions across complex supply chains.", points:["Environmental risk and resilience","Supply chain intelligence","Automation of evidence intensive processes","Data products for growers and producers"], video:"/sector-agri.mp4", poster:"/sector-agri-poster.jpg", filmTitle:"Turning field data into clearer choices." },
  { id:"manufacturing", number:"03", title:"Manufacturing & industry", line:"Practical intelligence for real operations.", copy:"We turn the data already present in processes, equipment and teams into useful insight. Then we automate the work that slows people down.", points:["Operational analytics","Process and workflow automation","Predictive insight","Human centred digital tools"], filmTitle:"A manufacturing story is taking shape." },
];

export default function Sectors(){return <main><SiteHeader/><PageHero eyebrow="Sectors / 02" title={<>Deep context.<br/><em>Practical change.</em></>} intro="Our work is strongest where decisions matter, systems are complex and trust has to be earned."/><section className="sector-pages section-pad">{sectors.map(s=><article id={s.id} key={s.id}><div className="sector-index">{s.number}</div><div className="sector-copy"><p className="mini-label">{s.title}</p><h2>{s.line}</h2><p>{s.copy}</p><Link href="/contact" className="arrow-link">Talk about your challenge <span>↗</span></Link></div><div className="sector-side"><div className={`sector-film${s.video ? "" : " film-placeholder"}`} style={s.poster ? {backgroundImage:`url(${sitePath(s.poster)})`} : undefined}>{s.video ? <video autoPlay muted loop playsInline preload="metadata" poster={sitePath(s.poster)} aria-hidden="true"><source src={sitePath(s.video)} type="video/mp4"/></video> : <div className="placeholder-grid"><i/><i/><i/></div>}<div className="sector-film-shade"/><strong>{s.filmTitle}</strong></div><ul>{s.points.map(p=><li key={p}>{p}</li>)}</ul></div></article>)}</section><PageFooter/></main>}
