import type { Metadata } from "next";
import { PageFooter, SiteHeader } from "../site-chrome";
import { sitePath } from "../site-path";
import ReadinessForm from "./readiness-form";

export const metadata:Metadata={title:"AI Readiness Roadmap",description:"Understand where AI can create value for your organisation and how prepared you are to adopt it effectively.",openGraph:{images:[{url:"/ai-readiness-roadmap.png",width:1341,height:684,alt:"AI Readiness Roadmap"}]}};

const dimensions=["People","Processes","Data","Technology"];

export default function AIReadiness(){return <main className="readiness-page"><SiteHeader/><section className="readiness-hero section-pad"><div><p className="mini-label">Coming soon from Tekh</p><h1>Know where AI can create value <em>before you invest.</em></h1><p className="lead">The AI Readiness Health Check gives you an independent view of your opportunities, your current capability and the practical next steps that matter.</p><a className="button button-light" href="#waiting-list">Join the waiting list <span>↓</span></a></div><div className="readiness-brand"><img src={sitePath("/ai-readiness-roadmap.png")} alt="AI Readiness Roadmap"/></div></section><section className="readiness-dimensions">{dimensions.map(item=><span key={item}>{item}</span>)}</section><section className="readiness-overview section-pad"><div className="section-label">The health check</div><div className="split-heading"><h2>Move from interest<br/><em>to informed action.</em></h2><div><p className="lead">Every organisation works differently. We evaluate the conditions around AI, not just the technology itself.</p><p>That gives you a clear view of where AI could deliver meaningful improvements, where it is unlikely to add value and what needs to change first.</p></div></div><div className="readiness-outcomes"><article><span>Understand</span><h3>See your current position clearly</h3><p>Build a shared understanding of your organisation’s readiness, strengths and constraints.</p></article><article><span>Assess</span><h3>Prioritise worthwhile opportunities</h3><p>Focus on uses of AI that connect to genuine needs and measurable business value.</p></article><article><span>Recommend</span><h3>Leave with practical next steps</h3><p>Receive tailored recommendations and a clear roadmap for moving forward.</p></article></div></section><section className="readiness-includes section-pad"><div><p className="mini-label">What you will receive</p><h2>A decision ready view of your AI opportunity.</h2></div><ul><li>A clear assessment of your AI readiness</li><li>Prioritised opportunities for creating value</li><li>Practical recommendations tailored to your organisation</li><li>A roadmap for your next steps</li></ul></section><section id="waiting-list" className="readiness-waitlist section-pad"><div><p className="mini-label">Early access</p><h2>Be among the first.</h2><p className="lead">Join the waiting list for product updates, early availability and opportunities to help shape the service.</p></div><ReadinessForm/></section><PageFooter/></main>}
